// const fs = require('fs');
// const glob = require('glob');
// const axios = require('axios');

// const apiKey = process.env.OPENAI_API_KEY;

// if (!apiKey) {
//   console.error("No API key provided!");
//   process.exit(1);
// }

// console.log("AI detection started");
// console.log("API key present:", !!apiKey);

// // 1️⃣ Get all TypeScript files in the Angular project
// function getAllCodeFiles() {
//   return glob.sync('src/**/*.ts', { absolute: true });
// }

// // 2️⃣ Read file contents
// function readFiles(files) {
//   return files.map(file => fs.readFileSync(file, 'utf-8')).join('\n\n');
// }

// // 3️⃣ Ask OpenAI to estimate AI-generated likelihood
// async function detectAIUsage(code) {
//   try {
//     const response = await axios.post(
//       'https://api.openai.com/v1/chat/completions',
//       {
//         model: 'gpt-4o-mini',  // lightweight, fast, cheaper
//         messages: [
//           {
//             role: 'system',
//             content: 'You are an AI detection tool.'
//           },
//           {
//             role: 'user',
//             content: 'Analyze the following code and return only a number between 0 and 100 indicating the likelihood that this code was generated by AI.'
//           },
//           {
//             role: 'user',
//             content: code
//           }
//         ],
//         temperature: 0
//       },
//       {
//         headers: {
//           'Authorization': `Bearer ${apiKey}`,
//           'Content-Type': 'application/json'
//         }
//       }
//     );

//     // Extract the number from the response
//     const output = response.data.choices[0].message.content.trim();
//     const percentage = output.match(/\d+/);
//     return percentage ? parseInt(percentage[0], 10) : null;

//   } catch (error) {
//     console.error("Error detecting AI usage:", error.response?.data || error.message);
//     return null;
//   }
// }

// async function main() {
//   const files = getAllCodeFiles();
//   if (files.length === 0) {
//     console.log("No TypeScript files found in src/");
//     return;
//   }

//   const code = readFiles(files);

//   const result = await detectAIUsage(code);
  
//   if (result !== null) {
//     console.log(`AI-generated content likelihood: ${result}%`);
//   } else {
//     console.log("AI detection could not compute a percentage.");
//   }
// }

// main();
